name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      #- name: Run tests
      #  run: |
      #    pytest pytest.py
      - name: Build Docker image
        run: |
          docker pull mertpolatt/tasks-app
