name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install Kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v1.24.1/kind-linux-amd64
          chmod +x kind
          mv kind /usr/local/bin/
      - name: Create Kind cluster
        run: |
          kind create cluster
      - name: Load Docker image
        run: |
          kubectl apply -f kind-config.yaml
          kind load docker-image merttpolat/tasks-app:latest
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
